services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - ${HOME}/.neko-words:/root/.neko-words

  web:
    build: ./web
    restart: always
    ports:
      - "3007:80"
    depends_on:
      - server
